Web/Models/ErrorViewModel.cs
namespace DocumnetParserProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Web/Controllers/DropdownListController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Common.Interfaces;

namespace DocumnetParserProject.Controllers;

public class DropdownListController:Controller
{
    private readonly ICurrencyService _currencyService;

    public DropdownListController(ICurrencyService currencyService)
    {
        _currencyService = currencyService;
    }

    public JsonResult CurrencyList(string term)
    {
        return Json(_currencyService.GetDropdownList(term));
    }
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using Database.ModelFilter;
using Microsoft.AspNetCore.Mvc;
using DocumnetParserProject.Models;
using Services.Common.Interfaces;
using Services.TransactionServices.Interfaces;

namespace DocumnetParserProject.Controllers;

public class HomeController : Controller
{
    private readonly ITransactionService _transactionService;
    
    public HomeController(ITransactionService transactionService)
    {
        _transactionService = transactionService;
        
    }
    public IActionResult Index()
    {
       
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Upload( IFormFile file)
    {
        await _transactionService.ProcessData(file);
        return Ok();
    }
    public async Task<JsonResult> GetList(OperationFilter filter)
    {
        var res = await _transactionService.GetList(filter);
        return Json(res);
    }
    
    public async Task<IActionResult> Operation()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="container">
        <div class="row">
             <form id="data" method="post" enctype="multipart/form-data">
                    <label for="FileName" class="form-label"></label>
                    <input class="form-control" type="file" id="FileName">
                </form>
        </div>
        <div class="row">
            <button style="margin: 12px" class="btn btn-primary col-4" id="btnSubmit">Upload</button>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#btnSubmit").click(function(e) {
            var formData = new FormData(document.forms.item(0));
            let file = $('#FileName').prop("files")[0];
            formData.append('file', file);
             e.preventDefault();
            $.ajax({
                url:"@Url.Action("Upload", "Home")",
                type: 'POST',
                   data: formData,
                   cache: false,
                   contentType: false,
                   processData: false,
                   success: (res) => {
                      alert("Uploaded")
                      $('#FileName').val("")
                   },
                   error:(res)=>{
                      alert(res.responseJSON.title)
                        $('#FileName').val("")
                    }
            });
        });
    </script>
}

Web/Views/Home/Operation.cshtml
<div class="container">
	
	<form id="filterForm">
		<div class="row">
			<div class="form-group col-3">
				<label for="CurrencyCode">Currency</label>
				<select class="js-example-basic-single col-4 form-control" id="CurrencyCode">
					<option value=""></option>
				</select>
			</div>
			<div class="form-group col-3">
				<label for="Status">Status</label>
				<select class="select2 form-control" id="Status">
					<option value=""></option>
					<option value="0">A</option>
					<option value="1">R</option>
					<option value="2">D</option>
				</select>
			</div>
			<div class="form-group col-3">
				<label for="From">From</label>
				<input class="form-control" type="date" id="From">
			</div>
			<div class="form-group col-3">
				<label for="To">To</label>
				<input class="form-control" type="date" id="To">
			</div>
			
		</div>
		
	</form>
	<div class="row" style="padding-top: 30px;">
		<div class="form-group col-3">
			<button class="form-control btn btn-primary" id="search">Search</button>
		</div>
	</div>
	<div class="row" style="padding-top: 30px;">
		<table id="example" class="display" style="width:100%">
			<thead>
			<tr>
				<th>ID</th>
				<th>Payment</th>
				<th>Status</th>
			</tr>
			</thead>
		</table>
	</div>

</div>
@section Scripts
{
	<script>
	
	$('.js-example-basic-single').select2({
      ajax: {
        url: '@Url.Action("CurrencyList", "DropdownList")',
        dataType: 'json',
        processResults: function (data) {
                          return {
                              results: $.map(data, function (item) {
                                  return {
                                      text: item.text,
                                      id: item.id
                                  }
                              })
                          };
                      }
      },
      
    });
	var tb = $('#example').DataTable({
                 ajax: 
                 { 
					 url:'@Url.Action("GetList", "Home")',
					 data: function (d){
                     					 d.operationStatus = $("#Status").val();
										 d.from = $("#From").val();
										 d.to = $("#To").val();
										 d.currencyCode = $("#CurrencyCode").val();
                     				 }
				 },
				 
                 processing: true,
                 serverSide: true, 
                 ordering: false,
                 searching: false,
                 columns:
                 [
						 {data : "id"},
						 {data : "payment"},
						 {data : "status"}
                 ]  
             });
	$("#search").click(function (){
    		tb.draw();
    	});
	</script>
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Test Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Operation">Operations</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Nguyen The Van - <a asp-area="" asp-controller="Home" asp-action="Operation">Operations</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
 <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
 <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
 <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
 <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>